# Generated by Django 4.2.8 on 2025-12-20 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "batch",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)]
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                ("section", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                ("department_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                ("period_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                (
                    "period_no",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
            options={
                "db_table": "period",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "teacher_email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=50)),
                ("verified", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
            ],
            options={
                "db_table": "teacher",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_field",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.class",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        db_column="teacher_email",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "subject",
                "unique_together": {("course", "class_field")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=20)),
                ("verified", models.BooleanField(default=False)),
                (
                    "class_field",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.class",
                    ),
                ),
            ],
            options={
                "db_table": "student",
                "unique_together": {("roll_no", "class_field")},
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("otp", models.CharField(blank=True, max_length=4, null=True)),
                ("otp_generated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.period"
                    ),
                ),
            ],
            options={
                "db_table": "session",
            },
        ),
        migrations.AddField(
            model_name="period",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.subject"
            ),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_email", models.EmailField(max_length=254)),
                ("device_uuid", models.UUIDField()),
                ("fingerprint_hash", models.CharField(max_length=64)),
                (
                    "integrity_level",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("BASIC", "Basic"),
                            ("FAIL", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ANDROID", "Android"), ("IOS", "iOS")], max_length=10
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "device",
                "indexes": [
                    models.Index(
                        fields=["user_email", "active"],
                        name="device_user_em_0ffee9_idx",
                    )
                ],
                "unique_together": {("user_email", "device_uuid", "fingerprint_hash")},
            },
        ),
        migrations.AddField(
            model_name="class",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.department"
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Present"), ("A", "Absent"), ("R", "Retry")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_email",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["is_active"], name="session_is_acti_c6f5d4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="session",
            unique_together={("period", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("subject", "day_of_week", "period_no")},
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("department", "batch", "semester", "section")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["status"], name="attendance_status_a068a7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("session", "student")},
        ),
    ]
