# Generated by Django 4.2.8 on 2025-12-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_class_completed_at_class_completed_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['period', 'date'], name='session_period__37eb37_idx'),
        ),
    ]
