# Generated by Django 4.2.8 on 2025-12-27 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_session_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.class')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.teacher')),
            ],
            options={
                'db_table': 'announcement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='period',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to='core.class')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.teacher')),
            ],
            options={
                'db_table': 'teacher_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='teacher_not_teacher_3095c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeriodTimeSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.teacher')),
            ],
            options={
                'db_table': 'period_time_slot',
                'ordering': ['period_no'],
                'unique_together': {('teacher', 'period_no')},
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.announcement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements', to='core.student')),
            ],
            options={
                'db_table': 'announcement_read',
                'unique_together': {('announcement', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['class_obj', '-created_at'], name='announcemen_class_o_37b8d7_idx'),
        ),
    ]
