# Generated by Django 4.2.8 on 2025-12-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_time_slots_and_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'class_teacher',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_classes', to='core.teacher'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['coordinator'], name='class_coordin_0567d4_idx'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments_made', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='core.class'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to='core.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('class_obj', 'teacher')},
        ),
    ]
