# Generated by Django 4.2.8 on 2025-12-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_coordinator_and_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_enrollments_made', to='core.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.subject')),
            ],
            options={
                'db_table': 'subject_enrollment',
                'indexes': [models.Index(fields=['subject'], name='subject_enr_subject_4e8f72_idx'), models.Index(fields=['student'], name='subject_enr_student_b47e20_idx')],
                'unique_together': {('subject', 'student')},
            },
        ),
    ]
