# Generated by Django 4.2.8 on 2025-12-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subject_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_appointments_made', to='core.teacher')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_organizations', to='core.teacher')),
            ],
            options={
                'db_table': 'organization_admin',
                'unique_together': {('organization', 'teacher')},
            },
        ),
    ]
