# Generated by Django 4.2.8 on 2026-02-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_organization_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='class_mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='proximity_radius',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('R', 'Retry'), ('X', 'Proxy')], default='A', max_length=1),
        ),
    ]
